extends: airbnb
parser: babel-eslint
env:
  browser: true
plugins:
  - react
  - jsx-a11y
  - import
rules:
  arrow-body-style:
    - off
  arrow-parens:
    - off
  brace-style:
    - warn
    - stroustrup
  class-methods-use-this:
    - off
  indent:
    - warn
    - 4
    - SwitchCase: 1
  import/first:
    - off
  import/imports-first:
    - off
  import/no-extraneous-dependencies:
    - off
  import/no-unresolved:
    - off
  import/prefer-default-export:
    - off
  import/extensions:
    - off
  jsx-a11y/anchor-has-content:
    - off
  jsx-a11y/href-no-hash:
    - off
  jsx-a11y/img-has-alt:
    - off
  jsx-a11y/no-static-element-interactions:
    - off
  jsx-quotes:
    - off
  key-spacing:
    - warn
    - align: value
  max-len:
    - off
  new-cap:
    - warn
    - capIsNewExceptions:
      - CSSModules
      - Features
  no-case-declarations:
    - off
  no-console:
    - warn
  no-else-return:
    - off
  no-lonely-if:
    - off
  no-mixed-operators:
    - off
  no-multi-spaces:
    - off
  no-plusplus:
    - off
  no-restricted-syntax:
    - off
  no-return-await:
    - off
  no-shadow:
    - error
  no-tabs:
    - off
  no-throw-literal:
    - off
  no-underscore-dangle:
    - off
  no-use-before-define:
    - error
    - functions: false
  padded-blocks:
    - off
  prefer-template:
    - off
  quotes:
    - off
  react/jsx-closing-bracket-location:
    - off
  react/jsx-indent:
    - warn
    - 4
  react/require-default-props:
    - off
  react/jsx-indent-props:
    - off
  react/no-array-index-key:
    - off
  react/no-danger:
    - off
  react/no-did-mount-set-state:
    - off
  react/no-string-refs:
    - off
  react/prefer-stateless-function:
    - off
  react/prop-types:
    - off